version: '3'

services:
  minio:
    depends_on:
      - rabbitmq
    image: hackathon/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-miniosecretkey}
    command: server /data

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    hostname: rabbitmq  # See https://hub.docker.com/_/rabbitmq/
    expose:
      - "5672"
      - "15672"
    ports:
      - "15672:15672"
    tmpfs:
      - /var/lib/rabbitmq
    volumes:
      - /etc/rabbitmq
    read_only: true
